# Code Quality
include:
  - template: Code-Quality.gitlab-ci.yml

code_quality:
  inherit:
    default: false
  artifacts:
    paths: [gl-code-quality-report.json]
  allow_failure: true

# Script testing
default:
  image: registry.gitlab.com/luigi311/av1-docker:latest
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    # Install Dependencies
    - apt-get update && apt-get install -y parallel time gawk jq python3 python3-pip python-is-python3
    - pip3 install numpy
    # Grab first two arguments to test only
    - mv arugments/arguments.aomenc arguments/arguments.temp
    - head -n 2 arguments/arguments.temp > arguments/arguments.aomenc
    - mv arguments/arguments.x265 arguments/arguments.temp
    - head -n 2 arguments/arguments.temp > arguments/arguments.x265
    - mv arguments/arguments.svt-av1 arguments/arguments.temp
    - head -n 2 arguments/arguments.temp > arguments/arguments.svt-av1
    # Download test videos from SVT-AV1
    - for url in raw.githubusercontent.com/OpenVisualCloud/SVT-AV1-Resources/master randomderp.com; do curl -LO https://$url/video.tar.gz && break; done 
    - tar xf video.tar.gz

stages:
  - test

validation-aomenc:
  script:
    - ./run.sh --input "bus_cif.y4m" --output "output" --csv "stats.csv" --encworkers 2 --metricworkers 1 --flags arguments.aomenc --threads 2 --q --quality 40 --preset 6 --enc aomenc
    - cat stats.csv
    - if [ "$(grep -c '^,\|,,\|,$' stats.csv)" -ge 1 ]; then exit 1; fi

bd_rate-aomenc:
  script:
    - ./run.sh --input "bus_cif.y4m" --output "output" --csv "stats.csv" --encworkers 2 --metricworkers 1 --flags arguments.aomenc --threads 2 --q --bd steps --preset 6 --enc aomenc
    - cat stats.csv
    - cat stats_bd_rates.csv
    - if [ "$(grep -c '^,\|,,\|,$' stats.csv)" -ge 1 ]; then exit 1; fi

simple-aomenc:
  script:
    - ./run.sh --input "bus_cif.y4m" --output "output" --csv "stats.csv" --bd steps --enc aomenc --decode
    - cat stats.csv
    - cat stats_bd_rates.csv
    - if [ "$(grep -c '^,\|,,\|,$' stats.csv)" -ge 1 ]; then exit 1; fi

validation-svt-av1:
  script:
    - ./run.sh --input "bus_cif.y4m" --output "output" --csv "stats.csv" --encworkers 2 --metricworkers 1 --flags arguments.svt-av1 --threads 4 --cq --quality 40 --preset 8 --enc svt-av1
    - cat stats.csv
    - if [ "$(grep -c '^,\|,,\|,$' stats.csv)" -ge 1 ]; then exit 1; fi

bd_rate-svt-av1:
  script:
    - ./run.sh --input "bus_cif.y4m" --output "output" --csv "stats.csv" --encworkers 2 --metricworkers 1 --flags arguments.svt-av1 --threads 4 --cq --bd steps --preset 8 --enc svt-av1
    - cat stats.csv
    - cat stats_bd_rates.csv
    - if [ "$(grep -c '^,\|,,\|,$' stats.csv)" -ge 1 ]; then exit 1; fi

simple-svt-av1:
  script:
    - ./run.sh --input "bus_cif.y4m" --output "output" --csv "stats.csv" --bd steps --enc svt-av1 --decode
    - cat stats.csv
    - cat stats_bd_rates.csv
    - if [ "$(grep -c '^,\|,,\|,$' stats.csv)" -ge 1 ]; then exit 1; fi

validation-x265:
  script:
    - ./run.sh --input "bus_cif.y4m" --output "output" --csv "stats.csv" --encworkers 2 --metricworkers 1 --flags arguments.x265 --threads 2 --crf --quality 40 --preset 0 --enc x265
    - cat stats.csv
    - if [ "$(grep -c '^,\|,,\|,$' stats.csv)" -ge 1 ]; then exit 1; fi

bd_rate-x265:
  script:
    - ./run.sh --input "bus_cif.y4m" --output "output" --csv "stats.csv" --encworkers 2 --metricworkers 1 --flags arguments.x265 --threads 2 --crf --bd steps --preset 0 --enc x265
    - cat stats.csv
    - cat stats_bd_rates.csv
    - if [ "$(grep -c '^,\|,,\|,$' stats.csv)" -ge 1 ]; then exit 1; fi

simple-x265:
  script:
    - ./run.sh --input "bus_cif.y4m" --output "output" --csv "stats.csv" --bd steps --enc x265 --decode
    - cat stats.csv
    - cat stats_bd_rates.csv
    - if [ "$(grep -c '^,\|,,\|,$' stats.csv)" -ge 1 ]; then exit 1; fi
    